### ISSUE TITLE
[Feature] Authors should be an actual database table

### ISSUE THREAD

**Issue by Tiefseetauchner** [Tiefseetauchner/online-media-shelf#26]

**Comment by ReiniVanBerch** [comment]
:D

**Comment by Tiefseetauchner** [comment]
@ReiniVanBerch Plz fix

```
  🥺 
👉🏻  👈🏻 
```

**Comment by Tiefseetauchner** [comment]
- Add new Model "Author" to Domain.Models
  - Id (Guid)
  - Name (string, 64)
  - Works (List\<ItemData\>)
- ItemData.Authors auf List\<Author\> umstellen
- AuthorRepository : CrudRepository\<Author, Guid\>, IAuthorRepostory + IAuthorRepostory : ICrudRepository\<Author, Guid\> (an z.B. ShelfRepository orientieren)
- Repository in UnitOfWork hinterlegen
- ApplicationDbContext um DbSet<Author> erweitern 
- OnModelCreating neue n-m Beziehung (Wie bei Shelf)
- neue migration
  - `/usr/share/dotnet/dotnet ef migrations add --project OnlineMediaShelf.Domain/OnlineMediaShelf.Domain.csproj --startup-project OnlineMediaShelf.Domain/OnlineMediaShelf.Domain.csproj --context Tiefseetauchner.OnlineMediaShelf.Domain.ApplicationDbContext --configuration Debug AddAuthorsAsSeparateTable --output-dir Migrations`
